### ISSUE TITLE
Training the model on the GPU

### ISSUE THREAD

**Issue by syrinecheriaa** [BatsResearch/wiser#25]
I would like if there is a straight forward way to train the generative model on GPU? In fact, I don't find any parameter for this part of training, that can allow us to do so. 
Thank you.

**Comment by safranchik** [comment]
Hello syrinecheriaa,

Thank you for your message! We currently do not have GPU implementation of the generative models. This is because our generative models to implement sparse matrix algebra, which runs faster on the CPU. For instance, we have found that training the linked HMM on a GPU takes about twice as long as training it on a CPU.

Please refer to the following [issue](https://github.com/BatsResearch/wiser/issues/21) for tips on how to speed up the training of generative models.

Hope this helps!
